package com.risc.backend.game;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.risc.backend.game.dto.GameView;
import com.risc.backend.game.dto.PlayerView;
import com.risc.backend.game.dto.TerritoryView;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import org.junit.jupiter.api.Test;

class GameRuleAutomationTest {
  private static final Path LOG_PATH = Path.of("target", "game-rule-test-log.md");

  @Test
  void coversGameRulesAndWritesReadableLog() throws IOException {
    List<String> report = new ArrayList<>();
    report.add("# RISC automated game-rule test log");
    report.add("");
    report.add("This log is generated by `GameRuleAutomationTest`.");
    report.add("");

    try {
      coverSetupRules(report);
      coverMoveAttackResourceRules(report);
      coverUpgradeRules(report);
      coverValidationRules(report);
      coverCombatRules(report);
      coverDefeatAndWinRules(report);
      report.add("## Final result");
      report.add("");
      report.add("All automated game-rule checks passed.");
      report.add("");
    } finally {
      Files.createDirectories(LOG_PATH.getParent());
      Files.writeString(LOG_PATH, String.join(System.lineSeparator(), report));
    }
  }

  private void coverSetupRules(List<String> report) {
    section(report, "Setup: reserves and abandoned starting territory");
    GameEngine engine = new GameEngine(
        List.of(PlayerId.GREEN, PlayerId.BLUE),
        List.of(
            territory("G1", PlayerId.GREEN, 1, 2, 0, List.of("G2")),
            territory("G2", PlayerId.GREEN, 1, 2, 0, List.of("G1", "G3")),
            territory("G3", PlayerId.GREEN, 1, 2, 0, List.of("G2")),
            territory("B1", PlayerId.BLUE, 1, 2, 0, List.of())),
        new FixedRandom());

    engine.commitPlacement(PlayerId.GREEN, Map.of("G1", 4, "G2", 5, "G3", 0), List.of("G3"));
    engine.commitPlacement(PlayerId.BLUE, Map.of("B1", 9), List.of());

    GameView view = engine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals(0, player(view, PlayerId.GREEN).reserveUnits());
    assertEquals(5, territory(view, "G1").units());
    assertEquals(6, territory(view, "G2").units());
    assertEquals(0, territory(view, "G3").units());
    assertEquals(null, territory(view, "G3").owner());

    IllegalArgumentException error = assertThrows(
        IllegalArgumentException.class,
        () -> new GameEngine(
            List.of(PlayerId.GREEN, PlayerId.BLUE),
            List.of(
                territory("GX", PlayerId.GREEN, 1, 0, 0, List.of()),
                territory("BX", PlayerId.BLUE, 1, 0, 0, List.of())),
            new FixedRandom()).commitPlacement(PlayerId.GREEN, Map.of("GX", 0), List.of("GX")));
    assertTrue(error.getMessage().contains("keep at least one"));

    report.add("- Green placed all 9 reserve units: G1 got 4, G2 got 5, G3 got 0.");
    report.add("- G3 was abandoned and became unoccupied with 0 units.");
    report.add("- Invalid setup that abandons every starting territory is rejected.");
    report.add("");
  }

  private void coverMoveAttackResourceRules(List<String> report) {
    section(report, "Simultaneous turn: move before attack, reinforcements, resources");
    GameEngine engine = new GameEngine(
        List.of(PlayerId.GREEN, PlayerId.BLUE),
        List.of(
            territory("G1", PlayerId.GREEN, 1, 10, 4, List.of("G2", "B1")),
            territory("G2", PlayerId.GREEN, 2, 1, 1, List.of("G1", "U1")),
            territory("U1", null, 3, 3, 2, List.of("G2")),
            territory("B1", PlayerId.BLUE, 1, 10, 4, List.of("G1", "B2")),
            territory("B2", PlayerId.BLUE, 1, 1, 1, List.of("B1"))),
        new FixedRandom(19, 0, 19, 0));

    engine.commitPlacement(PlayerId.GREEN, Map.of("G1", 6, "G2", 3), List.of());
    engine.commitPlacement(PlayerId.BLUE, Map.of("B1", 0, "B2", 9), List.of());
    engine.startOrdersPhase(List.of("Orders phase"));
    engine.resolveCommittedTurn(List.of());

    engine.validateOrders(PlayerId.GREEN, List.of(
        new OrderCommand(OrderType.MOVE, "G1", "G2", 2, PlayerId.GREEN),
        new OrderCommand(OrderType.MOVE, "G2", "U1", 1, PlayerId.GREEN),
        new OrderCommand(OrderType.ATTACK, "G1", "B1", 3, PlayerId.GREEN)));
    engine.resolveCommittedTurn(List.of(
        new OrderCommand(OrderType.MOVE, "G1", "G2", 2, PlayerId.GREEN),
        new OrderCommand(OrderType.MOVE, "G2", "U1", 1, PlayerId.GREEN),
        new OrderCommand(OrderType.ATTACK, "G1", "B1", 3, PlayerId.GREEN)));

    GameView view = engine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals(PlayerId.GREEN.name(), territory(view, "B1").owner());
    assertEquals(4, territory(view, "B1").units());
    assertEquals(PlayerId.GREEN.name(), territory(view, "U1").owner());
    assertEquals(2, territory(view, "U1").units());
    assertTrue(player(view, PlayerId.GREEN).resources().get(ResourceType.FOOD.name()) > 0);
    assertLogOrder(view.lastLog(), "Move departure: G1", "Attack departure: G1");

    report.add("- Green first banked resources with a no-order turn.");
    report.add("- Green then moved 2 units from G1 to G2, moved 1 unit from G2 into adjacent unoccupied U1, and attacked B1 with 3 units in the same committed turn.");
    report.add("- The engine log confirms movement resolved before attacks.");
    report.add("- Green occupied U1 and captured B1; after end-of-turn reinforcement U1 had 2 units and B1 had 4 units.");
    appendEngineLog(report, view.lastLog());
  }

  private void coverUpgradeRules(List<String> report) {
    section(report, "Technology and unit upgrades");
    GameEngine engine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 5, 100, List.of("B1")),
            territory("B1", PlayerId.BLUE, 1, 5, 100, List.of("G1"))),
        new FixedRandom());

    engine.resolveCommittedTurn(List.of());
    engine.validateOrders(PlayerId.GREEN, List.of(OrderCommand.upgradeTech(PlayerId.GREEN)));
    engine.resolveCommittedTurn(List.of(OrderCommand.upgradeTech(PlayerId.GREEN)));

    GameView afterTech = engine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals(2, player(afterTech, PlayerId.GREEN).maxTechnologyLevel());
    assertTrue(afterTech.lastLog().stream().anyMatch(line -> line.contains("UPGRADE_TECH from 1 to 2 costs 50")));

    engine.validateOrders(PlayerId.GREEN, List.of(
        OrderCommand.upgradeUnit("G1", 1, PlayerId.GREEN, UnitLevel.BASIC, UnitLevel.LEVEL_2)));
    engine.resolveCommittedTurn(List.of(
        OrderCommand.upgradeUnit("G1", 1, PlayerId.GREEN, UnitLevel.BASIC, UnitLevel.LEVEL_2)));

    GameView afterUnit = engine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals(1, territory(afterUnit, "G1").unitCounts().get(UnitLevel.LEVEL_2.name()));
    assertTrue(afterUnit.lastLog().stream().anyMatch(line -> line.contains("costs 11 TECHNOLOGY")));

    GameEngine lockedEngine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 5, 100, List.of("B1")),
            territory("B1", PlayerId.BLUE, 1, 5, 100, List.of("G1"))),
        new FixedRandom());
    lockedEngine.resolveCommittedTurn(List.of());
    IllegalArgumentException error = assertThrows(
        IllegalArgumentException.class,
        () -> lockedEngine.validateOrders(PlayerId.GREEN, List.of(
            OrderCommand.upgradeTech(PlayerId.GREEN),
            OrderCommand.upgradeUnit("G1", 1, PlayerId.GREEN, UnitLevel.BASIC, UnitLevel.LEVEL_2))));
    assertTrue(error.getMessage().contains("Cannot upgrade to LEVEL_2"));

    report.add("- Tech upgrade from level 1 to 2 spent 50 TECHNOLOGY and completed for the next turn.");
    report.add("- After tech level 2 was available, Green upgraded 1 BASIC unit to LEVEL_2 for 11 TECHNOLOGY.");
    report.add("- A same-turn tech upgrade does not unlock higher unit levels immediately.");
    appendEngineLog(report, afterTech.lastLog());
    appendEngineLog(report, afterUnit.lastLog());
  }

  private void coverValidationRules(List<String> report) {
    section(report, "Invalid orders are rejected");
    GameEngine engine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 3, 1, 0, List.of("G2", "B1")),
            territory("G2", PlayerId.GREEN, 3, 0, 0, List.of("G1")),
            territory("B1", PlayerId.BLUE, 1, 0, 0, List.of("G1"))),
        new FixedRandom());
    engine.resolveCommittedTurn(List.of());

    assertRejected(report, () -> engine.validateOrders(
        PlayerId.GREEN,
        List.of(new OrderCommand(OrderType.MOVE, "G1", "B1", 1, PlayerId.GREEN))),
        "Move targets must belong");
    assertRejected(report, () -> engine.validateOrders(
        PlayerId.GREEN,
        List.of(new OrderCommand(OrderType.ATTACK, "G2", "B1", 1, PlayerId.GREEN))),
        "Attacks must target adjacent territories");
    assertRejected(report, () -> engine.validateOrders(
        PlayerId.GREEN,
        List.of(new OrderCommand(OrderType.ATTACK, "G1", "B1", 2, PlayerId.GREEN))),
        "Not enough FOOD");
    report.add("");
  }

  private void coverCombatRules(List<String> report) {
    section(report, "Combat: d20 rolls, defender ties, bonuses, combined attackers");
    GameEngine tieEngine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 10, 0, List.of("B1")),
            territory("B1", PlayerId.BLUE, 1, 10, 0, List.of("G1"))),
        new FixedRandom(4, 4));
    tieEngine.resolveCommittedTurn(List.of());
    tieEngine.resolveCommittedTurn(List.of(new OrderCommand(OrderType.ATTACK, "G1", "B1", 1, PlayerId.GREEN)));
    GameView tieView = tieEngine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals(PlayerId.BLUE.name(), territory(tieView, "B1").owner());
    assertTrue(tieView.lastLog().stream().anyMatch(line -> line.contains("attacker loses 1 BASIC")));

    GameEngine bonusEngine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 10, 10, List.of("B1")),
            territory("B1", PlayerId.BLUE, 1, 10, 10, List.of("G1"))),
        new FixedRandom(19, 1, 1, 1, 1, 1));
    bonusEngine.resolveCommittedTurn(List.of());
    bonusEngine.resolveCommittedTurn(List.of(
        OrderCommand.upgradeUnit("G1", 1, PlayerId.GREEN, UnitLevel.BASIC, UnitLevel.LEVEL_1),
        OrderCommand.upgradeUnit("B1", 1, PlayerId.BLUE, UnitLevel.BASIC, UnitLevel.LEVEL_1),
        new OrderCommand(OrderType.ATTACK, "G1", "B1", 2, PlayerId.GREEN)));
    GameView bonusView = bonusEngine.view(PlayerId.GREEN, "RULES", List.of());
    assertTrue(bonusView.lastLog().stream().anyMatch(line -> line.contains("A LEVEL_1 (20+1=21) vs D BASIC")));
    assertTrue(bonusView.lastLog().stream().anyMatch(line -> line.contains("A BASIC (2+0=2) vs D LEVEL_1")));

    GameEngine multiEngine = preparedThreePlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 10, 10, List.of("R1")),
            territory("B1", PlayerId.BLUE, 1, 10, 10, List.of("R1")),
            territory("R1", PlayerId.RED, 1, 0, 0, List.of("G1", "B1")),
            territory("R2", PlayerId.RED, 1, 0, 0, List.of())),
        new FixedRandom(1, 19, 0, 0, 19));
    multiEngine.resolveCommittedTurn(List.of());
    multiEngine.resolveCommittedTurn(List.of(
        OrderCommand.upgradeUnit("G1", 1, PlayerId.GREEN, UnitLevel.BASIC, UnitLevel.LEVEL_1),
        new OrderCommand(OrderType.ATTACK, "G1", "R1", 2, PlayerId.GREEN),
        new OrderCommand(OrderType.ATTACK, "B1", "R1", 1, PlayerId.BLUE)));
    GameView multiView = multiEngine.view(PlayerId.GREEN, "RULES", List.of());
    assertTrue(multiView.lastLog().stream().anyMatch(line -> line.contains("Battle queue at R1")));
    assertTrue(multiView.lastLog().stream().anyMatch(line -> line.contains("Green from G1")));
    assertTrue(multiView.lastLog().stream().anyMatch(line -> line.contains("Blue from B1")));

    report.add("- Equal d20 totals are resolved in favor of the defender.");
    report.add("- Unit combat bonuses are included in the d20 total.");
    report.add("- Multiple attackers against the same target are queued in a server-chosen order.");
    appendEngineLog(report, tieView.lastLog());
    appendEngineLog(report, bonusView.lastLog());
    appendEngineLog(report, multiView.lastLog());
  }

  private void coverDefeatAndWinRules(List<String> report) {
    section(report, "Defeat and winning the game");
    List<Integer> winningRolls = new ArrayList<>();
    for (int i = 0; i < 24; i++) {
      winningRolls.add(i % 2 == 0 ? 19 : 0);
    }
    GameEngine engine = preparedTwoPlayerEngine(
        List.of(
            territory("G1", PlayerId.GREEN, 1, 20, 0, List.of("B1")),
            territory("B1", PlayerId.BLUE, 1, 0, 0, List.of("G1"))),
        new FixedRandom(winningRolls.stream().mapToInt(Integer::intValue).toArray()));
    engine.resolveCommittedTurn(List.of());
    engine.resolveCommittedTurn(List.of(new OrderCommand(OrderType.ATTACK, "G1", "B1", 11, PlayerId.GREEN)));

    GameView view = engine.view(PlayerId.GREEN, "RULES", List.of());
    assertEquals("GAME_OVER", view.phase());
    assertEquals(PlayerId.GREEN.name(), view.winner());
    assertTrue(view.lastLog().stream().anyMatch(line -> line.contains("Blue has no territories left")));
    assertTrue(view.lastLog().stream().anyMatch(line -> line.contains("Green is the last faction")));

    report.add("- Green captured Blue's only territory.");
    report.add("- Blue was eliminated at 0 territories.");
    report.add("- Green became the winner and the game entered GAME_OVER.");
    appendEngineLog(report, view.lastLog());
  }

  private GameEngine preparedTwoPlayerEngine(List<TerritoryDefinition> map, Random random) {
    GameEngine engine = new GameEngine(List.of(PlayerId.GREEN, PlayerId.BLUE), map, random);
    Map<String, Integer> greenAllocations = new java.util.LinkedHashMap<>();
    Map<String, Integer> blueAllocations = new java.util.LinkedHashMap<>();
    for (TerritoryDefinition definition : map) {
      if (definition.initialOwner() == PlayerId.GREEN) {
        greenAllocations.put(definition.name(), greenAllocations.isEmpty() ? 9 : 0);
      } else if (definition.initialOwner() == PlayerId.BLUE) {
        blueAllocations.put(definition.name(), blueAllocations.isEmpty() ? 9 : 0);
      }
    }
    engine.commitPlacement(PlayerId.GREEN, greenAllocations, List.of());
    engine.commitPlacement(PlayerId.BLUE, blueAllocations, List.of());
    engine.startOrdersPhase(List.of("Orders phase"));
    return engine;
  }

  private GameEngine preparedThreePlayerEngine(List<TerritoryDefinition> map, Random random) {
    GameEngine engine = new GameEngine(List.of(PlayerId.GREEN, PlayerId.BLUE, PlayerId.RED), map, random);
    engine.commitPlacement(PlayerId.GREEN, Map.of("G1", 9), List.of());
    engine.commitPlacement(PlayerId.BLUE, Map.of("B1", 9), List.of());
    engine.commitPlacement(PlayerId.RED, Map.of("R1", 0, "R2", 9), List.of());
    engine.startOrdersPhase(List.of("Orders phase"));
    return engine;
  }

  private TerritoryDefinition territory(
      String name,
      PlayerId owner,
      int size,
      int food,
      int technology,
      List<String> neighbors) {
    EnumMap<ResourceType, Integer> production = new EnumMap<>(ResourceType.class);
    production.put(ResourceType.FOOD, food);
    production.put(ResourceType.TECHNOLOGY, technology);
    return new TerritoryDefinition(name, 0, 0, owner, size, Map.copyOf(production), neighbors, List.of());
  }

  private PlayerView player(GameView view, PlayerId playerId) {
    return view.players().stream().filter(player -> player.id().equals(playerId.name())).findFirst().orElseThrow();
  }

  private TerritoryView territory(GameView view, String name) {
    return view.territories().stream().filter(territory -> territory.name().equals(name)).findFirst().orElseThrow();
  }

  private void section(List<String> report, String title) {
    report.add("## " + title);
    report.add("");
  }

  private void appendEngineLog(List<String> report, List<String> lines) {
    report.add("");
    report.add("Engine log:");
    for (String line : lines) {
      report.add("- `" + line.replace("`", "'") + "`");
    }
    report.add("");
  }

  private void assertRejected(List<String> report, ThrowingRunnable action, String expectedMessagePart) {
    IllegalArgumentException error = assertThrows(IllegalArgumentException.class, action::run);
    assertTrue(error.getMessage().contains(expectedMessagePart));
    report.add("- Rejected invalid order: `" + error.getMessage().replace("`", "'") + "`");
  }

  private void assertLogOrder(List<String> log, String first, String second) {
    int firstIndex = indexOf(log, first);
    int secondIndex = indexOf(log, second);
    assertNotNull(firstIndex >= 0 ? firstIndex : null);
    assertNotNull(secondIndex >= 0 ? secondIndex : null);
    assertTrue(firstIndex < secondIndex);
  }

  private int indexOf(List<String> lines, String text) {
    for (int i = 0; i < lines.size(); i++) {
      if (lines.get(i).contains(text)) {
        return i;
      }
    }
    return -1;
  }

  @FunctionalInterface
  private interface ThrowingRunnable {
    void run();
  }

  private static final class FixedRandom extends Random {
    private final int[] values;
    private int index;

    private FixedRandom(int... values) {
      this.values = values;
    }

    @Override
    public int nextInt(int bound) {
      if (index >= values.length) {
        return 0;
      }
      return Math.floorMod(values[index++], bound);
    }
  }
}
